using System;
using System.IO;
using System.Windows.Forms;
using ZXing;
using ZXing.QrCode;

namespace Oblik_polotiv
{
    public partial class frmFlightDetails : UserControl
    {
        public Flight flight { get; set; }
        public frmFlightDetails()
        {
            InitializeComponent();
            
        }
        public void EnterData()
        {
            if (flight != null)
            {
                flightRoute.Text = flight.from_City + "( " + flight.from_Country + " ) - "
                     + flight.to_City + "( " + flight.to_Country + " ) ";
                lblCarrier.Text = flight.carrier;
                lblRoute.Text = flight.from_Airport + " " + flight.from_City + "( " + flight.from_Country +
                    " ) → " + flight.to_Airport + flight.to_City + "( " + flight.to_Country + " ) ";
                if (flight.cls.Equals("First"))
                    lblPrice.Text = "Price: " + (flight.from_Price * 2) + "$";
                else if (flight.cls.Equals("Business"))
                    lblPrice.Text = "Price: " + (flight.from_Price * 1.5) + "$";
                else
                    lblPrice.Text = "Price: " + flight.from_Price + "$";
                lblDepart.Text = flight.depart.Hour + ":" + flight.depart.Minute;
                lblArrive.Text = flight.arrive.Hour + ":" + flight.arrive.Minute;
                lblFliTime.Text = (flight.arrive.Hour - flight.depart.Hour) + "h " + (flight.arrive.Minute - flight.depart.Minute);
                lstBoxPilots.Items.AddRange(flight.pilots.ToArray());
                var writer = new BarcodeWriter();
                writer.Format = BarcodeFormat.QR_CODE; 
                var text = flight.ToString();
                var result = writer.Write(text);
                picBoxQR.Image = result;
                lblID.Text = "№" + flight.id;
            }
        }

        private void btnSaveFlight_Click(object sender, EventArgs e)
        {
            if(saveFileDialog.ShowDialog() == DialogResult.OK)
            {
                string name = saveFileDialog.FileName;
                string text = flight.ToString();
                text += "\n\n This file is generated by FlightNow";
                File.WriteAllText(name, text);
            }
        }       
    }
}
